package scalograf
package model.enums

import enumeratum.values.{StringCirceEnum, StringEnum, StringEnumEntry}

sealed abstract class Units(val value: String) extends StringEnumEntry

object Units extends StringEnum[Units] with StringCirceEnum[Units] {
  val values: IndexedSeq[Units] = findValues

  // Misc
  case object None extends Units("none")
  case object Short extends Units("short")
  case object Percent extends Units("percent")
  case object PercentUnit extends Units("percentunit")
  case object Humidity extends Units("humidity")
  case object Decibel extends Units("dB")
  case object Hexadecimal0x extends Units("hex0x")
  case object Hexadecimal extends Units("hex")
  case object ScientificNotation extends Units("sci")
  case object LocaleFormat extends Units("locale")
  case object Pixels extends Units("pixel")
  // Acceleration
  case object MetersPerSecSquared extends Units("accMS2")
  case object FeetPerSecSquared extends Units("accFS2")
  case object Gunit extends Units("accG")
  // Angle
  case object Degrees extends Units("degree")
  case object Radians extends Units("radian")
  case object Gradian extends Units("grad")
  case object ArcMinutes extends Units("arcmin")
  case object ArcSeconds extends Units("arcsec")
  // Area
  case object SquareMeters extends Units("areaM2")
  case object SquareFeet extends Units("areaF2")
  case object SquareMiles extends Units("areaMI2")
  // Computation
  case object FLOPPerSec extends Units("flops")
  case object MFLOPPerSec extends Units("mflops")
  case object GFLOPPerSec extends Units("gflops")
  case object TFLOPPerSec extends Units("tflops")
  case object PFLOPPerSec extends Units("pflops")
  case object EFLOPPerSec extends Units("eflops")
  case object ZFLOPPerSec extends Units("zflops")
  case object YFLOPPerSec extends Units("yflops")
  // Concentration
  case object PartsPerMillion extends Units("ppm")
  case object PartsPerBillion extends Units("conppb")
  case object NanogramPerCubicMeter extends Units("conngm3")
  case object NanogramPerNormalCubicMeter extends Units("conngNm3")
  case object MicrogramPerCubicMeter extends Units("conμgm3")
  case object MicrogramPerNormalCubicMeter extends Units("conμgNm3")
  case object MilligramPerCubicMeter extends Units("conmgm3")
  case object MilligramPerNormalCubicMeter extends Units("conmgNm3")
  case object GramPerCubicMeter extends Units("congm3")
  case object GramPerNormalCubicMeter extends Units("congNm3")
  case object MilligramsPerDecilitre extends Units("conmgdL")
  case object MillimolesPerLitre extends Units("conmmolL")
  // Currency
  case object Dollars extends Units("currencyUSD")
  case object Pounds extends Units("currencyGBP")
  case object Euro extends Units("currencyEUR")
  case object Yen extends Units("currencyJPY")
  case object Rubles extends Units("currencyRUB")
  case object Hryvnias extends Units("currencyUAH")
  case object Real extends Units("currencyBRL")
  case object DanishKrone extends Units("currencyDKK")
  case object IcelandicKrona extends Units("currencyISK")
  case object NorwegianKrone extends Units("currencyNOK")
  case object SwedishKrona extends Units("currencySEK")
  case object CzechKoruna extends Units("currencyCZK")
  case object SwissFranc extends Units("currencyCHF")
  case object PolishZloty extends Units("currencyPLN")
  case object Bitcoin extends Units("currencyBTC")
  case object MilliBitcoin extends Units("currencymBTC")
  case object MicroBitcoin extends Units("currencyμBTC")
  case object SouthAfricanRand extends Units("currencyZAR")
  case object IndianRupee extends Units("currencyINR")
  case object SouthKoreanWon extends Units("currencyKRW")
  // Data (IEC)
  case object Bits extends Units("bits")
  case object Bytes extends Units("bytes")
  case object Kibibytes extends Units("kbytes")
  case object Mebibytes extends Units("mbytes")
  case object Gibibytes extends Units("gbytes")
  case object Tebibytes extends Units("tbytes")
  case object Pebibytes extends Units("pbytes")
  // Data (Metric)
  case object BitsMetric extends Units("decbits")
  case object BytesMetric extends Units("decbytes")
  case object Kilobytes extends Units("deckbytes")
  case object Megabytes extends Units("decmbytes")
  case object Gigabytes extends Units("decgbytes")
  case object Terabytes extends Units("dectbytes")
  case object Petabytes extends Units("decpbytes")
  // Data Rate
  case object PacketsPerSec extends Units("pps")
  case object BitsPerSec extends Units("bps")
  case object BytesPerSec extends Units("Bps")
  case object KilobytesPerSec extends Units("KBs")
  case object KilobitsPerSec extends Units("Kbits")
  case object MegabytesPerSec extends Units("MBs")
  case object MegabitsPerSec extends Units("Mbits")
  case object GigabytesPerSec extends Units("GBs")
  case object GigabitsPerSec extends Units("Gbits")
  case object TerabytesPerSec extends Units("TBs")
  case object TerabitsPerSec extends Units("Tbits")
  case object PetabytesPerSec extends Units("PBs")
  case object PetabitsPerSec extends Units("Pbits")
  // Date & Time
  case object ISODateTime extends Units("dateTimeAsIso")
  case object USDateTime extends Units("dateTimeAsUS")
  case object FromNow extends Units("dateTimeFromNow")
  // Energy
  case object Watt extends Units("watt")
  case object Kilowatt extends Units("kwatt")
  case object Megawatt extends Units("megwatt")
  case object Gigawatt extends Units("gwatt")
  case object Milliwatt extends Units("mwatt")
  case object WattPerSquareMeter extends Units("Wm2")
  case object VoltAmpere extends Units("voltamp")
  case object KilovoltAmpere extends Units("kvoltamp")
  case object VoltAmpereReactive extends Units("voltampreact")
  case object KilovoltAmpereReactive extends Units("kvoltampreact")
  case object WattHour extends Units("watth")
  case object WattHourPerKilogram extends Units("watthperkg")
  case object KilowattHour extends Units("kwatth")
  case object KilowattMin extends Units("kwattm")
  case object AmpereHour extends Units("amph")
  case object KiloampereHour extends Units("kamph")
  case object MilliampereHour extends Units("mamph")
  case object Joule extends Units("joule")
  case object ElectronVolt extends Units("ev")
  case object Ampere extends Units("amp")
  case object Kiloampere extends Units("kamp")
  case object Milliampere extends Units("mamp")
  case object Volt extends Units("volt")
  case object Kilovolt extends Units("kvolt")
  case object Millivolt extends Units("mvolt")
  case object DecibelMilliwatt extends Units("dBm")
  case object Ohm extends Units("ohm")
  case object Kiloohm extends Units("kohm")
  case object Megaohm extends Units("Mohm")
  case object Farad extends Units("farad")
  case object Microfarad extends Units("µfarad")
  case object Nanofarad extends Units("nfarad")
  case object Picofarad extends Units("pfarad")
  case object Femtofarad extends Units("ffarad")
  case object Henry extends Units("henry")
  case object Millihenry extends Units("mhenry")
  case object Microhenry extends Units("µhenry")
  case object Lumens extends Units("lumens")
  // Flow
  case object GallonsPerMinute extends Units("flowgpm")
  case object CubicMetersPerSec extends Units("flowcms")
  case object CubicFeetPerSec extends Units("flowcfs")
  case object CubicFeetPerMinute extends Units("flowcfm")
  case object LitrePerHour extends Units("litreh")
  case object LitrePerMinute extends Units("flowlpm")
  case object MilliLitrePerMinute extends Units("flowmlpm")
  case object Lux extends Units("lux")
  // Force
  case object NewtonMeters extends Units("forceNm")
  case object KilonewtonMeters extends Units("forcekNm")
  case object Newtons extends Units("forceN")
  case object Kilonewtons extends Units("forcekN")
  // Hash Rate
  case object HashesPerSec extends Units("Hs")
  case object KilohashesPerSec extends Units("KHs")
  case object MegahashesPerSec extends Units("MHs")
  case object GigahashesPerSec extends Units("GHs")
  case object TerahashesPerSec extends Units("THs")
  case object PetahashesPerSec extends Units("PHs")
  case object ExahashesPerSec extends Units("EHs")
  // Mass
  case object Milligram extends Units("massmg")
  case object Gram extends Units("massg")
  case object Kilogram extends Units("masskg")
  case object MetricTon extends Units("masst")
  // Length
  case object Millimeter extends Units("lengthmm")
  case object Feet extends Units("lengthft")
  case object Meter extends Units("lengthm")
  case object Kilometer extends Units("lengthkm")
  case object Mile extends Units("lengthmi")
  // Pressure
  case object Millibars extends Units("pressurembar")
  case object Bars extends Units("pressurebar")
  case object Kilobars extends Units("pressurekbar")
  case object Pascals extends Units("pressurepa")
  case object Hectopascals extends Units("pressurehpa")
  case object Kilopascals extends Units("pressurekpa")
  case object InchesOfMercury extends Units("pressurehg")
  case object PSI extends Units("pressurepsi")
  // Radiation
  case object Becquerel extends Units("radbq")
  case object Curie extends Units("radci")
  case object Gray extends Units("radgy")
  case object Rad extends Units("radrad")
  case object Sievert extends Units("radsv")
  case object MilliSievert extends Units("radmsv")
  case object MicroSievert extends Units("radusv")
  case object Rem extends Units("radrem")
  case object Exposure extends Units("radexpckg")
  case object Roentgen extends Units("radr")
  case object SievertPerHour extends Units("radsvh")
  case object MilliSievertPerHour extends Units("radmsvh")
  case object MicroSievertPerHour extends Units("radusvh")
  // Rotational Speed
  case object RevolutionsPerMinute extends Units("rotrpm")
  case object HertzRotational extends Units("rothz")
  case object RadiansPerSecond extends Units("rotrads")
  case object DegreesPerSecond extends Units("rotdegs")
  // Temperature
  case object Celsius extends Units("celsius")
  case object Fahrenheit extends Units("fahrenheit")
  case object Kelvin extends Units("kelvin")
  // Time
  case object Hertz extends Units("hertz")
  case object Nanoseconds extends Units("ns")
  case object Microseconds extends Units("µs")
  case object Milliseconds extends Units("ms")
  case object Seconds extends Units("s")
  case object Minutes extends Units("m")
  case object Hours extends Units("h")
  case object Days extends Units("d")
  case object DurationMilliseconds extends Units("dtdurationms")
  case object DurationSeconds extends Units("dtdurations")
  case object DurationHoursMinutesSeconds extends Units("dthms")
  case object DurationDaysHoursMinutesSeconds extends Units("dtdhms")
  case object Timeticks extends Units("timeticks")
  case object ClockMilliseconds extends Units("clockms")
  case object ClockSeconds extends Units("clocks")
  // Throughput
  case object CountsPerSec extends Units("cps")
  case object OpsPerSec extends Units("ops")
  case object RequestsPerSec extends Units("reqps")
  case object ReadsPerSec extends Units("rps")
  case object WritesPerSec extends Units("wps")
  case object IOOpsPerSec extends Units("iops")
  case object CountsPerMinute extends Units("cpm")
  case object OpsPerMinute extends Units("opm")
  case object ReadsPerMinute extends Units("rpm")
  case object WritesPerMinute extends Units("wpm")
  // Velocity
  case object MetersPerSecond extends Units("velocityms")
  case object KilometersPerHour extends Units("velocitykmh")
  case object MilesPerHour extends Units("velocitymph")
  case object Knot extends Units("velocityknot")
  // Volume
  case object Millilitre extends Units("mlitre")
  case object Litre extends Units("litre")
  case object CubicMeter extends Units("m3")
  case object NormalCubicMeter extends Units("Nm3")
  case object CubicDecimeter extends Units("dm3")
  case object Gallons extends Units("gallons")

}
